import type { Metadata } from "next";
import { Geist, Geist_Mono  } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const drukWide = localFont({
  src: "../public/fonts/DrukWideBold.ttf",
  variable: "--font-druk",
  weight: "700",
});

const Apercu = localFont({
  src: "../public/fonts/apercu_regular_pro.otf",
  variable: "--font-apercu",
  weight: "400",
});
export const metadata: Metadata = {
  title: "IAMBIC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
